### ISSUE TITLE
Can you give me the PDF of this paper? Not online search

### ISSUE THREAD

**Issue by wangxinyue11** [marcusangeloni/facialparts_age#1]
Can you give me the PDF of this paper? Not online search

**Comment by marcusangeloni** [comment]
> Can you give me the PDF of this paper? Not online search

Thank you for the interest in our research. The paper will be present in ICCV 2019 (November 2nd) and after that it will be publicly available in IEEE Xplore and in CVF Open Access (http://openaccess.thecvf.com/menu.py).

If you need the PDF now, please, send an e-mail to me (marcus.angeloni@ic.unicamp.br) and I send to you a pre-print version.

Best regards.

**Comment by marcusangeloni** [comment]
Paper is publicly available in http://openaccess.thecvf.com/content_ICCVW_2019/papers/CEFRL/Angeloni_Age_Estimation_From_Facial_Parts_Using_Compact_Multi-Stream_Convolutional_Neural_ICCVW_2019_paper.pdf
